fundfloat/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('superadmin/', include('superadmin.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

superadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from superadmin import views


app_name = 'superadmin'

urlpatterns = [
    path('',views.index.as_view(),name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('profile', views.profile.as_view(), name='profile'),

    path('dashboard', views.dashboard.as_view(), name='dashboard'),

    
    path('userlist', views.userlist.as_view(), name='userlist'),
    path('usercreate', views.usercreate.as_view(), name='usercreate'),
    path('useredit/<int:id>', views.usercreate.as_view(), name='useredit'),
    
    path('courselist', views.courselist.as_view(), name='courselist'),
    path('coursecreate', views.coursecreate.as_view(), name='coursecreate'),
    path('courseedit/<int:id>', views.coursecreate.as_view(), name='courseedit'),
     
    path('instructorlist', views.instructorlist.as_view(), name='instructorlist'),
    path('instructorcreate', views.instructorcreate.as_view(), name='instructorcreate'),
    path('editinstructor/<int:id>', views.instructorcreate.as_view(), name='editinstructor'),

    path('paymentlist', views.paymentlist.as_view(), name='paymentlist'),

         
    path('categorybloglist', views.categorybloglist.as_view(), name='categorybloglist'),
    path('categoryblogcreate', views.categoryblogcreate.as_view(), name='categoryblogcreate'),
    path('categoryblogedit/<int:id>', views.categoryblogcreate.as_view(), name='categoryblogedit'),
    
         
    path('bloglist', views.bloglist.as_view(), name='bloglist'),
    path('blogcreate', views.blogcreate.as_view(), name='blogcreate'),
    path('blogedit/<int:id>', views.blogcreate.as_view(), name='blogedit'),

    
]

superadmin/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
# from rest_framework import serializers
# from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.dispatch import receiver


from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create your models here.

GENDER_CHOICES = (
        ('1', 'Male'),
        ('2', 'Female'),
    )

USER_TYPE_CHOICES = (
      (1, 'superadmin'),
      (2, 'Sub Admin'),
      (3, 'Trainer'),
      (4, 'Student'),
  )

STATUS_CHOICES = (
      ('unpaid', 'unpaid'),
      ('paid', 'paid'),
      ('cancelled', 'cancelled'),
  )


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )
        user.admin = 2
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.admin = 3
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.admin = 1
        user.save(using=self._db)
        return user






class User(AbstractBaseUser):
    unique_id = models.TextField(null=True,unique=True)
    firstname = models.TextField(null=True)
    lastname = models.TextField(null=True)
    phone = models.TextField(null=True,unique=True)
    code = models.TextField(null=True)
    profession = models.TextField(null=True)
    email = models.EmailField(max_length=255, blank=True, null=True,unique=True)
    password =  models.CharField(max_length=255, blank=True,null=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=1, blank=True, null=True)
    image = models.ImageField(upload_to='student', null=True, blank=True,max_length=400)
    is_active = models.BooleanField(default=True)
    is_premium = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)


    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.name


    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.admin

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin





    objects = UserManager()




class Courses(models.Model):
    type = models.TextField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    subtitle = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='course', null=True, blank=True)
    phone = models.TextField(null=True, blank=True)
    email = models.TextField(null=True, blank=True)
    profession = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)






class Instructors(models.Model):
    name = models.TextField(null=True, blank=True)
    designation = models.TextField(null=True, blank=True)
    course = ArrayField(models.TextField(), null=True, blank=True)
    image = models.ImageField(upload_to='instructor', null=True, blank=True)    
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)




class BlogCategory(models.Model):
    title = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)




class Blogs(models.Model):
    category = models.ForeignKey(BlogCategory,on_delete=models.CASCADE)
    title = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='blog', null=True, blank=True)    
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

superadmin/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, JsonResponse
from superadmin.helper import renderhelper, is_ajax
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import redirect
from superadmin.custom_permision import LoginRequiredMixin, AdminLoginRequiredMixin
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from superadmin.models import *
# from superadmin.serializer import *

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.db.models import Q

from django.http import JsonResponse
from django.template.loader import render_to_string, get_template

from itertools import chain
from django.core.files.base import ContentFile
from django.urls import reverse
from django.http import HttpResponseRedirect

# from superadmin.helper import renderhelper, is_ajax, sendQAPushNotification,link_callback
# from docx import Document
from datetime import datetime
import random



# Create your views here.
class index(View):
    def get(self, request):
        context = {}
        if request.user.id:
            return redirect('superadmin:dashboard')
        else:
            return renderhelper(request, 'login', 'login', context)

    def post(self, request):
        context = {}
        username = request.POST['username']
        password = request.POST['password']
        print(username)
        print(password)
        user = authenticate(username=username, password=password)
        # return HttpResponse(user)

        if user:
            login(request, user)
            return redirect('superadmin:dashboard')
        else:
            context['username'] = username
            context['password'] = password
            messages.info(request, 'Invalid Username or Password')
            return renderhelper(request, 'login', 'login', context)




class dashboard(LoginRequiredMixin, View):
    def get(self, request):
        context = {}
        return renderhelper(request, 'home', 'index', context)

class Logout(LoginRequiredMixin,View):
    def get(self, request):
        logout(request)
        return redirect('superadmin:login')

class profile(LoginRequiredMixin,View):
    def get(self, request):
        context = {}
        return renderhelper(request, 'login', 'profile',context)
    
    def post(self, request):
        password_to_check = request.POST['oldpassword']
        newpassword = request.POST['newpassword']
        conpassword = request.POST['conpassword']
        password_matches = check_password(password_to_check, request.user.password)
        if password_matches:
            if newpassword == conpassword:
                user = User.objects.get(id=request.user.id)
                new_password = conpassword  # Replace 'new_password' with the new password
                user.set_password(new_password)
                user.pass_text = conpassword
                user.save()
                messages.info(request, 'Password changed')
                return renderhelper(request, 'login', 'profile')
            else:
                messages.info(request, 'new password not matching')
                context = {'oldpass': password_to_check, 'newpassword': newpassword, 'conpassword': conpassword}
                return renderhelper(request, 'login', 'profile', context)

        else:
            messages.info(request, 'Your old password is incorrect')
            context = {'oldpass': password_to_check,'newpassword':newpassword,'conpassword':conpassword}
            return renderhelper(request, 'login', 'profile', context)
        


class userlist(LoginRequiredMixin,View):
    def get(self, request, id=None):
        context = {}
        conditions = Q()
        # context['previllage'] = check_previllage(request, 'Course')
        if is_ajax(request):
            page = request.GET.get('page', 1)
            context['page'] = page
            status = request.GET.get('status')
            # search = request.GET.get("search")
            type = request.GET.get('type')
            if type == '1':
                id = request.GET.get('id')
                vl = request.GET.get('vl')
                cat = User.objects.get(id=id)
                if vl == '2':
                    cat.is_active = False
                else:
                    cat.is_active = True
                cat.save()
                messages.info(request, 'Successfully Updated')
            elif type == '2':
                id = request.GET.get('id')
                User.objects.filter(id=id).delete()
                messages.info(request, 'Successfully Deleted')
            # if search:
            #     conditions &= Q(eng_title__icontains=search)
            if status:
                conditions &= Q(is_active=status)
            data_list = User.objects.filter(conditions).order_by('-id')
            paginator = Paginator(data_list, 15)

            try:
                datas = paginator.page(page)
            except PageNotAnInteger:
                datas = paginator.page(1)
            except EmptyPage:
                datas = paginator.page(paginator.num_pages)
            context['datas'] = datas
            template = loader.get_template('superadmin/users/course-table.html')
            html_content = template.render(context, request)
            return JsonResponse({'status': True, 'template': html_content})

        data = User.objects.filter(user_type=4).order_by('-id')
        p = Paginator(data, 15)
        page_num = request.GET.get('page', 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context['datas'] = page
        context['page'] = page_num

        return renderhelper(request, 'users', 'users-view',context)

class usercreate(LoginRequiredMixin, View):
    def get(self, request, id=None):
        context = {}
        try:
            context['data'] =data= User.objects.get(id=id)
            

        except:
            context['data'] = None
        return renderhelper(request, 'users', 'users-create', context)

    def post(self, request, id=None):
        try:
            data = User.objects.get(id=id)
            messages.info(request, 'Successfully Updated')
        except:
            data = User()
            data.save()
            data.unique_id = 'FF'+str(data.id)+str(random.randint(0000,9999))
            messages.info(request, 'Successfully Added')

        image = request.FILES.get('imagefile')
        if image:
            data.image=image


       

        data.firstname=request.POST['firstname']
        data.lastname=request.POST['lastname']
        data.phone=request.POST['mobile']
        data.email=request.POST['email']
        data.profession=request.POST['profession']
        data.user_type=4
        

        data.save()



        return redirect('superadmin:userlist')


class courselist(LoginRequiredMixin,View):
    def get(self, request, id=None):
        context = {}
        conditions = Q()
        # context['previllage'] = check_previllage(request, 'Course')
        if is_ajax(request):
            page = request.GET.get('page', 1)
            context['page'] = page
            status = request.GET.get('status')
            # search = request.GET.get("search")
            type = request.GET.get('type')
            if type == '1':
                id = request.GET.get('id')
                vl = request.GET.get('vl')
                cat = Courses.objects.get(id=id)
                if vl == '2':
                    cat.is_active = False
                else:
                    cat.is_active = True
                cat.save()
                messages.info(request, 'Successfully Updated')
            elif type == '2':
                id = request.GET.get('id')
                Courses.objects.filter(id=id).delete()
                messages.info(request, 'Successfully Deleted')
            # if search:
            #     conditions &= Q(eng_title__icontains=search)
            if status:
                conditions &= Q(is_active=status)
            data_list = Courses.objects.filter(conditions).order_by('-id')
            paginator = Paginator(data_list, 15)

            try:
                datas = paginator.page(page)
            except PageNotAnInteger:
                datas = paginator.page(1)
            except EmptyPage:
                datas = paginator.page(paginator.num_pages)
            context['datas'] = datas
            template = loader.get_template('superadmin/course/course-table.html')
            html_content = template.render(context, request)
            return JsonResponse({'status': True, 'template': html_content})

        data = Courses.objects.all().order_by('-id')
        p = Paginator(data, 15)
        page_num = request.GET.get('page', 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context['datas'] = page
        context['page'] = page_num

        return renderhelper(request, 'course', 'course-view',context)

class coursecreate(LoginRequiredMixin, View):
    def get(self, request, id=None):
        context = {}
        try:
            context['data'] = Courses.objects.get(id=id)
        except:
            context['data'] = None
        return renderhelper(request, 'course', 'course-create', context)

    def post(self, request, id=None):
        try:
            data = Courses.objects.get(id=id)
            messages.info(request, 'Successfully Updated')
        except:
            data = Courses()
            messages.info(request, 'Successfully Added')

        image = request.FILES.get('imagefile')
        if image:
            data.image=image


       

        data.type=request.POST['course_type']
        data.title=request.POST['course_name']
        data.subtitle=request.POST['sub_content']
        data.phone=request.POST['mobile_number']

templates/superadmin/course/course-create.html
{% include 'superadmin/layouts/header.html' %}

<!--app-content open-->
<div class="main-content app-content mt-0">
    <div class="side-app">

        <!-- CONTAINER -->
        <div class="main-container container-fluid">

            <!-- PAGE-HEADER -->
            <div class="page-header">
                <h1 class="page-title">Courses</h1>
                <div>
                    <a class="btn btn-primary" href="{% url 'superadmin:courselist' %}"><i
                            class="side-menu__icon fe fe-eye mx-1"></i>View All</a>
                </div>
            </div>
            <!-- PAGE-HEADER END -->

            <!-- ROW OPEN -->
            <form method="post" enctype="multipart/form-data" >
                {% csrf_token %}
                    <div class="row">

                <div class="col-md-4 col-xl-4 col-12">
                    <div class="card">

                        <div class="card-body">
                            <form>
                                <div class="row">

                                    <div class="col-lg-12 col-sm-12 mb-4 mb-lg-0">
                                        <label for="#" class="form-label">Upload Course Thumbnail Image</label>
                                        <input type="file" class="dropify" data-bs-height="180" name="imagefile" {% if not data %}required{% endif %} accept=".jpg,.png,.jpeg" data-default-file="{{data.image.url}}" />
                                    </div>

                                </div>




                        </div>


                    </div>
                </div>

                <div class="col-md-8 col-xl-8 col-12">
                    <div class="card">

                        <div class="card-body">

                            <div class="row col-lg-12">
                                
                                <div class="form-group col-lg-6 col-12">
                                    <label for="#" class="form-label">Course Type</label>
                                    <select class="form-control" required name="course_type">
                                        <option value="">Select</option>
                                        <option value="Free" {% if data.type == 'Free' %}selected{% endif %}>Free</option>
                                        <option value="Paid" {% if data.type == 'Paid' %}selected{% endif %}>Paid</option>
                                    </select>
                                </div>
                               
                               <div class="form-group col-lg-6 col-12">
                                    <label for="#" class="form-label">Course Name</label>
                                    <input type="text" class="form-control" id="#" placeholder="Course Name" name="course_name" required value="{{data.title}}">
                                </div>
                               
                                <div class="form-group col-lg-6 col-12">
                                    <label for="#" class="form-label">Sub Content</label>
                                    <input type="text" class="form-control" id="#" placeholder="Sub Content" name="sub_content" required  value="{{data.subtitle}}">
                                </div>
                                <div class="form-group col-lg-6 col-12">
                                    <label for="#" class="form-label">Mobile Number</label>
                                    <input type="number" class="form-control" id="#" placeholder="Mobile Number" name="mobile_number" required  value="{{data.phone}}">
                                </div>
                                <div class="form-group col-lg-6 col-12">
                                    <label for="#" class="form-label">Email ID</label>
                                    <input type="email" class="form-control" id="#" placeholder="Email ID " name="email_id" required  value="{{data.email}}">
                                </div>
                                <div class="form-group col-lg-6 col-12">
                                    <label for="#" class="form-label">Profession</label>
                                    <input type="text" class="form-control" id="#" placeholder="Profession" name="profession" required value="{{data.profession}}">
                                </div>
                               
                               
                               
                                <div class="form-group col-lg-3 col-3">
                                    <button type="submit" class="btn btn-primary mt-4 mb-0" >Submit</button>
                                </div>

                               
                            </div>
                        </div>

                    </div>
                    <!-- ROW CLOSED -->


                </div>
                </form>
                <!-- CONTAINER END -->
            </div>
        </div>
        <!--app-content close-->

        {% include 'superadmin/layouts/footer.html' %}

templates/superadmin/course/course-table.html
<input type="hidden" id="url" name="url" value="{{request.path}}">
<input type="hidden" id="page" name="page" value="{{page}}">
{% if messages %}
<div id="message_div" class="succs-msg">
    {% for message in messages %}
    <label class="form-group" style="">
        <p style="color:green;">{{message}}</p>
    </label>
    {% endfor %}
</div>
{% endif %}
<table
class="table border-top table-bordered mb-0 table-hover  dataTables_wrapper dt-bootstrap5"
id="datatable-basic">
<thead>
    <tr>
        <th>Sl No</th>
        
        <th> Thumbnail</th>
        <th>Course Title</th>
        <th>sub content</th>
        <th>Phone</th>
        <th>email</th>
        <th>profession</th>
        <th>type</th>


        <th>Status</th>


        <th>Action</th>
    </tr>
</thead>
<tbody>
    {% if datas %}
    {% for i in datas %}
    <tr>
        <td>{{forloop.counter0|add:datas.start_index}}</td>
        
       
        
        <td>{% if i.image %}<img  class="avatar avatar-md br-7" src="{{i.image.url}}">{% endif %}</td>
                    
        <td>{{i.title}}</td>
        <td>{{i.subtitle}}</td>
        <td>{{i.phone}}</td>
        <td>{{i.email}}</td>
        <td>{{i.profession}}</td>
        <td>{{i.type}}</td>
        


        <td>
            <div class="material-switch">
                <input id="someSwitchOptionSuccess{{i.id}}" name="someSwitchOption001" type="checkbox" {% if i.is_active %}checked onclick="coursestatus({{i.id}},2)"{% else %}onclick="coursestatus({{i.id}},1)" {% endif %}  />
                <label for="someSwitchOptionSuccess{{i.id}}" class="label-success"></label>
            </div>
        </td>
        <td>


            <a class="btn btn-info btn-sm mb-1" href="{% url 'superadmin:courseedit' i.id %}"><i class="side-menu__icon fe fe-edit"></i></a>


                    <a class="btn btn-danger btn-sm mb-1" href="javascript:void(0)" onclick="delete_modal({{i.id}})"><i class="side-menu__icon fe fe-trash" ></i></a>


        </td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td colspan="9" align="center">
            No Data
        </td>
    </tr>
    {% endif %}

</tbody>
</table>



<div class="pagination_section">
    {% if datas %}
    Showing {{ datas.start_index }}-{{ datas.end_index }} of {{ datas.paginator.count }}
    {% endif %}
    <!--Pagination-->
    {% if datas.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if datas.has_previous %}
            <li class="page-item">
            <a class="page-link" href="javascript:void(0)" onclick="return filtercourse('{{ datas.previous_page_number }}');">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
            </li>
        {% endif %}
        {% if datas.number == 1 %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="True">First</a>
            </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="javascript:void(0)" onclick="return filtercourse('{{ 1 }}');">First</a></li>
        {% endif %}
        {% for i in datas.paginator.page_range %}
            {% if datas.number > i and i > datas.number|add:-5 %}
            <li class="page-item"><a class="page-link" href="javascript:void(0)" onclick="return filtercourse('{{ i }}');">{{ i }}</a></li>
            {% endif %}
            {% if datas.number == i %}
            <li class="page-item active" aria-current="page">
            <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
            </span>
            </li>
            {% endif  %}
            {% if datas.number < i and i < datas.number|add:5 %}
            <li class="page-item"><a class="page-link" href="javascript:void(0)" onclick="return filtercourse('{{ i }}');">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if datas.number == datas.paginator.num_pages %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Last</a>
            </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="javascript:void(0)" onclick="return filtercourse('{{ datas.paginator.num_pages }}');">Last</a></li>
        {% endif %}
        {% if datas.has_next %}
            <li class="page-item">
            <a class="page-link"  href="javascript:void(0)" onclick="return filtercourse('{{ datas.next_page_number }}');">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
            </li>
        {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<script>
 $("#message_div").fadeOut(3000);
</script>

templates/superadmin/course/course-view.html
{% include 'superadmin/layouts/header.html' %}

<!--app-content open-->
<div class="main-content app-content mt-0">
    <div class="side-app">

        <!-- CONTAINER -->
        <div class="main-container container-fluid">

            <!-- PAGE-HEADER -->
            <div class="page-header">
                <h1 class="page-title">Courses</h1>
                <div>
                    <a class="btn btn-primary" href="{% url 'superadmin:coursecreate' %}"><i
                            class="side-menu__icon fe fe-plus mx-1"></i>Add New</a>
                </div>
            </div>
            <!-- PAGE-HEADER END -->

            <!-- ROW OPEN -->
            <div class="row">
                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">List of All Courses</h3>
                        </div>
                        <div class="card-body">

                            <div class="table-responsive">

                               {% include 'superadmin/course/course-table.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
        <!-- CONTAINER END -->
    </div>
</div>



<div class="modal  fade" id="smalldes" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Other Details</h5>
                <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table border-top table-bordered mb-0" id="datatable-basic">
                    <thead>
                        <tr>
                           
                            <th>Price ($)</th>
                            <th>Price (AED)</th>
                            <th>Duration</th>
                            <th>Demo video</th>
                            <th>Course Description</th>
                            <th>Chat Room Thumbnail</th>
                            

                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                       
                            <td></td>
                            <td></td>
							<td></td>
                            <td></td>
							
                            <td></td>
							<td><img  class="avatar avatar-md br-7" src="assets/images_ex/user.png"></td>
                           

                        </tr>

                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-bs-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>


</div>
<!-- CONTAINER END -->
</div>
</div>
<!--app-content close-->





<div class="modal  fade" id="modaldemo5" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md modal-dialog-centered text-center" role="document">
        <div class="modal-content ">

            <div class="modal-body">
                <button aria-label="Close" class="btn-close position-absolute" data-bs-dismiss="modal"><span
                        aria-hidden="true">&times;</span></button>
                <i class="icon icon-close fs-70 text-danger lh-1 my-5 d-inline-block"></i>
                <h4 class="text-danger">Are You Sure Do You Want To Delete ?</h4>
                <p class="mg-b-20 mg-x-20">Item Will be Deleted Permanently</p>
                <input type="hidden" id="hid">
                <button class="btn btn-success" onclick="coursedelete()">Yes</button>
                <button aria-label="Close" class="btn btn-danger pd-x-25" data-bs-dismiss="modal">Cancel</button>
            </div>
            <div class="modal-footer">


            </div>
        </div>
    </div>
</div>
{% include 'superadmin/layouts/footer.html' %}