fundfloat/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('superadmin/', include('superadmin.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

superadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from superadmin import views


app_name = 'superadmin'

urlpatterns = [
    path('',views.index.as_view(),name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('profile', views.profile.as_view(), name='profile'),

    path('dashboard', views.dashboard.as_view(), name='dashboard'),

    
    path('userlist', views.userlist.as_view(), name='userlist'),
    path('usercreate', views.usercreate.as_view(), name='usercreate'),
    path('useredit/<int:id>', views.usercreate.as_view(), name='useredit'),
    
    path('courselist', views.courselist.as_view(), name='courselist'),
    path('coursecreate', views.coursecreate.as_view(), name='coursecreate'),
    path('courseedit/<int:id>', views.coursecreate.as_view(), name='courseedit'),
     
    path('instructorlist', views.instructorlist.as_view(), name='instructorlist'),
    path('instructorcreate', views.instructorcreate.as_view(), name='instructorcreate'),
    path('editinstructor/<int:id>', views.instructorcreate.as_view(), name='editinstructor'),

    path('paymentlist', views.paymentlist.as_view(), name='paymentlist'),

         
    path('categorybloglist', views.categorybloglist.as_view(), name='categorybloglist'),
    path('categoryblogcreate', views.categoryblogcreate.as_view(), name='categoryblogcreate'),
    path('categoryblogedit/<int:id>', views.categoryblogcreate.as_view(), name='categoryblogedit'),
    
         
    path('bloglist', views.bloglist.as_view(), name='bloglist'),
    path('blogcreate', views.blogcreate.as_view(), name='blogcreate'),
    path('blogedit/<int:id>', views.blogcreate.as_view(), name='blogedit'),

    
]

superadmin/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
# from rest_framework import serializers
# from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.dispatch import receiver


from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create your models here.

GENDER_CHOICES = (
        ('1', 'Male'),
        ('2', 'Female'),
    )

USER_TYPE_CHOICES = (
      (1, 'superadmin'),
      (2, 'Sub Admin'),
      (3, 'Trainer'),
      (4, 'Student'),
  )

STATUS_CHOICES = (
      ('unpaid', 'unpaid'),
      ('paid', 'paid'),
      ('cancelled', 'cancelled'),
  )


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )
        user.admin = 2
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.admin = 3
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.admin = 1
        user.save(using=self._db)
        return user






class User(AbstractBaseUser):
    unique_id = models.TextField(null=True,unique=True)
    firstname = models.TextField(null=True)
    lastname = models.TextField(null=True)
    phone = models.TextField(null=True,unique=True)
    code = models.TextField(null=True)
    profession = models.TextField(null=True)
    email = models.EmailField(max_length=255, blank=True, null=True,unique=True)
    password =  models.CharField(max_length=255, blank=True,null=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, default=1, blank=True, null=True)
    image = models.ImageField(upload_to='student', null=True, blank=True,max_length=400)
    is_active = models.BooleanField(default=True)
    is_premium = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)


    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.name


    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.admin

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin





    objects = UserManager()




class Courses(models.Model):
    type = models.TextField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    subtitle = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='course', null=True, blank=True)
    phone = models.TextField(null=True, blank=True)
    email = models.TextField(null=True, blank=True)
    profession = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)






class Instructors(models.Model):
    name = models.TextField(null=True, blank=True)
    designation = models.TextField(null=True, blank=True)
    course = ArrayField(models.TextField(), null=True, blank=True)
    image = models.ImageField(upload_to='instructor', null=True, blank=True)    
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)




class BlogCategory(models.Model):
    title = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)




class Blogs(models.Model):
    category = models.ForeignKey(BlogCategory,on_delete=models.CASCADE)
    title = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='blog', null=True, blank=True)    
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

superadmin/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, JsonResponse
from superadmin.helper import renderhelper, is_ajax
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import redirect
from superadmin.custom_permision import LoginRequiredMixin, AdminLoginRequiredMixin
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from superadmin.models import *
# from superadmin.serializer import *

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.db.models import Q

from django.http import JsonResponse
from django.template.loader import render_to_string, get_template

from itertools import chain
from django.core.files.base import ContentFile
from django.urls import reverse
from django.http import HttpResponseRedirect

# from superadmin.helper import renderhelper, is_ajax, sendQAPushNotification,link_callback
# from docx import Document
from datetime import datetime
import random



# Create your views here.
class index(View):
    def get(self, request):
        context = {}
        if request.user.id:
            return redirect('superadmin:dashboard')
        else:
            return renderhelper(request, 'login', 'login', context)

    def post(self, request):
        context = {}
        username = request.POST['username']
        password = request.POST['password']
        print(username)
        print(password)
        user = authenticate(username=username, password=password)
        # return HttpResponse(user)

        if user:
            login(request, user)
            return redirect('superadmin:dashboard')
        else:
            context['username'] = username
            context['password'] = password
            messages.info(request, 'Invalid Username or Password')
            return renderhelper(request, 'login', 'login', context)




class dashboard(LoginRequiredMixin, View):
    def get(self, request):
        context = {}
        return renderhelper(request, 'home', 'index', context)

class Logout(LoginRequiredMixin,View):
    def get(self, request):
        logout(request)
        return redirect('superadmin:login')

class profile(LoginRequiredMixin,View):
    def get(self, request):
        context = {}
        return renderhelper(request, 'login', 'profile',context)
    
    def post(self, request):
        password_to_check = request.POST['oldpassword']
        newpassword = request.POST['newpassword']
        conpassword = request.POST['conpassword']
        password_matches = check_password(password_to_check, request.user.password)
        if password_matches:
            if newpassword == conpassword:
                user = User.objects.get(id=request.user.id)
                new_password = conpassword  # Replace 'new_password' with the new password
                user.set_password(new_password)
                user.pass_text = conpassword
                user.save()
                messages.info(request, 'Password changed')
                return renderhelper(request, 'login', 'profile')
            else:
                messages.info(request, 'new password not matching')
                context = {'oldpass': password_to_check, 'newpassword': newpassword, 'conpassword': conpassword}
                return renderhelper(request, 'login', 'profile', context)

        else:
            messages.info(request, 'Your old password is incorrect')
            context = {'oldpass': password_to_check,'newpassword':newpassword,'conpassword':conpassword}
            return renderhelper(request, 'login', 'profile', context)
        


class userlist(LoginRequiredMixin,View):
    def get(self, request, id=None):
        context = {}
        conditions = Q()
        # context['previllage'] = check_previllage(request, 'Course')
        if is_ajax(request):
            page = request.GET.get('page', 1)
            context['page'] = page
            status = request.GET.get('status')
            # search = request.GET.get("search")
            type = request.GET.get('type')
            if type == '1':
                id = request.GET.get('id')
                vl = request.GET.get('vl')
                cat = User.objects.get(id=id)
                if vl == '2':
                    cat.is_active = False
                else:
                    cat.is_active = True
                cat.save()
                messages.info(request, 'Successfully Updated')
            elif type == '2':
                id = request.GET.get('id')
                User.objects.filter(id=id).delete()
                messages.info(request, 'Successfully Deleted')
            # if search:
            #     conditions &= Q(eng_title__icontains=search)
            if status:
                conditions &= Q(is_active=status)
            data_list = User.objects.filter(conditions).order_by('-id')
            paginator = Paginator(data_list, 15)

            try:
                datas = paginator.page(page)
            except PageNotAnInteger:
                datas = paginator.page(1)
            except EmptyPage:
                datas = paginator.page(paginator.num_pages)
            context['datas'] = datas
            template = loader.get_template('superadmin/users/course-table.html')
            html_content = template.render(context, request)
            return JsonResponse({'status': True, 'template': html_content})

        data = User.objects.filter(user_type=4).order_by('-id')
        p = Paginator(data, 15)
        page_num = request.GET.get('page', 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context['datas'] = page
        context['page'] = page_num

        return renderhelper(request, 'users', 'users-view',context)

class usercreate(LoginRequiredMixin, View):
    def get(self, request, id=None):
        context = {}
        try:
            context['data'] =data= User.objects.get(id=id)
            

        except:
            context['data'] = None
        return renderhelper(request, 'users', 'users-create', context)

    def post(self, request, id=None):
        try:
            data = User.objects.get(id=id)
            messages.info(request, 'Successfully Updated')
        except:
            data = User()
            data.save()
            data.unique_id = 'FF'+str(data.id)+str(random.randint(0000,9999))
            messages.info(request, 'Successfully Added')

        image = request.FILES.get('imagefile')
        if image:
            data.image=image


       

        data.firstname=request.POST['firstname']
        data.lastname=request.POST['lastname']
        data.phone=request.POST['mobile']
        data.email=request.POST['email']
        data.profession=request.POST['profession']
        data.user_type=4
        

        data.save()



        return redirect('superadmin:userlist')


class courselist(LoginRequiredMixin,View):
    def get(self, request, id=None):
        context = {}
        conditions = Q()
        # context['previllage'] = check_previllage(request, 'Course')
        if is_ajax(request):
            page = request.GET.get('page', 1)
            context['page'] = page
            status = request.GET.get('status')
            # search = request.GET.get("search")
            type = request.GET.get('type')
            if type == '1':
                id = request.GET.get('id')
                vl = request.GET.get('vl')
                cat = Courses.objects.get(id=id)
                if vl == '2':
                    cat.is_active = False
                else:
                    cat.is_active = True
                cat.save()
                messages.info(request, 'Successfully Updated')
            elif type == '2':
                id = request.GET.get('id')
                Courses.objects.filter(id=id).delete()
                messages.info(request, 'Successfully Deleted')
            # if search:
            #     conditions &= Q(eng_title__icontains=search)
            if status:
                conditions &= Q(is_active=status)
            data_list = Courses.objects.filter(conditions).order_by('-id')
            paginator = Paginator(data_list, 15)

            try:
                datas = paginator.page(page)
            except PageNotAnInteger:
                datas = paginator.page(1)
            except EmptyPage:
                datas = paginator.page(paginator.num_pages)
            context['datas'] = datas
            template = loader.get_template('superadmin/course/course-table.html')
            html_content = template.render(context, request)
            return JsonResponse({'status': True, 'template': html_content})

        data = Courses.objects.all().order_by('-id')
        p = Paginator(data, 15)
        page_num = request.GET.get('page', 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context['datas'] = page
        context['page'] = page_num

        return renderhelper(request, 'course', 'course-view',context)

class coursecreate(LoginRequiredMixin, View):
    def get(self, request, id=None):
        context = {}
        try:
            context['data'] = Courses.objects.get(id=id)
        except:
            context['data'] = None
        return renderhelper(request, 'course', 'course-create', context)

    def post(self, request, id=None):
        try:
            data = Courses.objects.get(id=id)
            messages.info(request, 'Successfully Updated')
        except:
            data = Courses()
            messages.info(request, 'Successfully Added')

        image = request.FILES.get('imagefile')
        if image:
            data.image=image


       

        data.type=request.POST['course_type']
        data.title=request.POST['course_name']
        data.subtitle=request.POST['sub_content']
        data.phone=request.POST['mobile_number']

templates/superadmin/layouts/header.html
{% load static %}
<!doctype html>
<html lang="en" dir="ltr">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'superadmin/assets/images_ex/icon-m.png' %}" />

    <!-- TITLE -->
    <title>Fundfloat Web Admin| Dashboard</title>

    <!-- BOOTSTRAP CSS -->
    <link id="style" href="{% static 'superadmin/assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- STYLE CSS -->
    <link href="{% static 'superadmin/assets/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'superadmin/assets/css/dark-style.css' %}" rel="stylesheet" />
    <link href="{% static 'superadmin/assets/css/transparent-style.css' %}" rel="stylesheet">
    <link href="{% static 'superadmin/assets/css/skin-modes.css' %}" rel="stylesheet" />

    <link href="{% static 'superadmin/assets/css/style-custom.css' %}" rel="stylesheet" />
    <!--- FONT-ICONS CSS -->
    <link href="{% static 'superadmin/assets/css/icons.css' %}" rel="stylesheet" />

    <!-- COLOR SKIN CSS -->
    <link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static 'superadmin/assets/colors/color1.css' %}" />

</head>

<body class="app sidebar-mini ltr light-mode">

   
    <!-- PAGE -->
    <div class="page">
        <div class="page-main">

            <!-- app-Header -->
            <div class="app-header header sticky">
                <div class="container-fluid main-container">
                    <div class="d-flex">
                        <a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-bs-toggle="sidebar" href="javascript:void(0)"></a>
                        <!-- sidebar-toggle-->
                        <a class="logo-horizontal " href="{% url 'superadmin:dashboard' %}">
                            <img src="{% static 'superadmin/assets/images_ex/logo.png' %}" class="header-brand-img desktop-logo" alt="logo">
                            <img src="{% static 'superadmin/assets/images_ex/logo-dark.png' %}" class="header-brand-img light-logo1"
                                alt="logo">
                        </a>
                        
                        <div class="d-flex order-lg-2 ms-auto header-right-icons">
                            
									 <div class="dropdown d-flex profile-1">
                                            <a href="javascript:void(0)" data-bs-toggle="dropdown" class="nav-link leading-none d-flex">
                                                <img src="{% static 'superadmin/assets/images_ex/user.png' %}" alt="profile-user"
                                                    class="avatar  profile-user brround cover-image">
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                                                <div class="drop-heading">
                                                    <div class="text-center">
                                                        <h5 class="text-dark mb-0 fs-14 fw-semibold">Username</h5>
                                                        <small class="text-muted">Web Admin</small>
                                                    </div>
                                                </div>
                                                <div class="dropdown-divider m-0"></div>
                                                <a class="dropdown-item" href="{% url 'superadmin:profile' %}">
                                                    <i class="dropdown-icon fe fe-user"></i> Profile
                                                </a>
												
                                                <a class="dropdown-item" href="{% url 'superadmin:logout' %}">
                                                    <i class="dropdown-icon fe fe-alert-circle"></i> Sign out
                                                </a>
                                            </div>
                                        </div>	
                           
                            
                        </div>
                    </div>
                </div>
            </div>
            <!-- /app-Header -->

            <!--APP-SIDEBAR-->
            <div class="sticky">
                <div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
                <div class="app-sidebar">
                    <div class="side-header">
                        <a class="header-brand1" href="{% url 'superadmin:dashboard' %}">
                            <img src="{% static 'superadmin/assets/images_ex/logo.png' %}" class="header-brand-img desktop-logo" alt="logo">
                            <img src="{% static 'superadmin/assets/images_ex/icon-m.png' %}" class="header-brand-img toggle-logo"
                                alt="logo">
                            <img src="{% static 'superadmin/assets/images_ex/icon-m.png' %}" class="header-brand-img light-logo" alt="logo">
                            <img src="{% static 'superadmin/assets/images_ex/logo-dark.png' %}" class="header-brand-img light-logo1"
                                alt="logo">
                        </a>
                        <!-- LOGO -->
                    </div>
                    <div class="main-sidemenu">
                        <div class="slide-left disabled" id="slide-left"><svg xmlns="http://www.w3.org/2000/svg"
                                fill="#7b8191" width="24" height="24" viewBox="0 0 24 24">
                                <path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z" />
                            </svg></div>
                        <ul class="side-menu">
                            <li class="sub-category">
                                <h3>Main</h3>
                            </li>
                            <li class="slide">
                                <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'superadmin:dashboard' %}"><i
                                        class="side-menu__icon fe fe-grid"></i><span
                                        class="side-menu__label">Dashboard</span></a>
                            </li>
                           
							
                           
                           
                           
                            <li class="slide">
                                <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'superadmin:userlist' %}">
								<i class="side-menu__icon fe fe-users"></i>
								<span class="side-menu__label">Users  </span>
								</a>
                            </li>
                            <li class="slide">
                                <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'superadmin:courselist' %}">
								<i class="side-menu__icon fe fe-book-open"></i>
								<span class="side-menu__label">Courses  </span>
								</a>
                            </li>

                            <li class="slide">
                                <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'superadmin:instructorlist' %}">
								<i class="side-menu__icon fe fe-user"></i>
								<span class="side-menu__label">Instructor </span>
								</a>
                            </li>
                            <li class="slide">
                                <a class="side-menu__item has-link" data-bs-toggle="slide" href="{% url 'superadmin:paymentlist' %}">
								<i class="side-menu__icon fe fe-dollar-sign"></i>
								<span class="side-menu__label">Payment </span>
								</a>
                            </li>
                            
							 <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)"><i class="side-menu__icon  fe fe-clipboard"></i><span class="side-menu__label">News</span><i class="angle fe fe-chevron-right"></i></a>
                                <ul class="slide-menu">
                                <li ><a href="{% url 'superadmin:categorybloglist' %}" class="slide-item">Category</a></li>
                                <li ><a href="{% url 'superadmin:bloglist' %}" class="slide-item">News</a></li>
                                  
                                   
                                </ul>
                            </li> 
                            <li class="slide">
                                <a class="side-menu__item has-link" data-bs-toggle="slide" href="notification-view.php">
								<i class="side-menu__icon fe fe-bell"></i>
								<span class="side-menu__label">Notification </span>
								</a>
                            </li>
                            <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)"><i class="side-menu__icon  fe fe-message-circle"></i><span class="side-menu__label">Chat</span><i class="angle fe fe-chevron-right"></i></a>
                                <ul class="slide-menu">
                                <li ><a href="chat-room-view.php" class="slide-item">Public Chat Room</a></li>
                                <li ><a href="course-chat-room.php" class="slide-item">Course Chat Room</a></li>
                                <li ><a href="webinar-chat-view.php" class="slide-item">Webinar  Chat Room</a></li>
                                  
                                   
                                </ul>
                            </li>
                            <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)"><i class="side-menu__icon  fe fe-rss"></i><span class="side-menu__label">Subscription</span><i class="angle fe fe-chevron-right"></i></a>
                                <ul class="slide-menu">
                                <li ><a href="subscription-view.php" class="slide-item">Subscriptions</a></li>
                                <li ><a href="subscriber-view.php" class="slide-item">Subscribers</a></li>
                               
                                  
                                   
                                </ul>
                            </li>
                           
                        </ul>
                        <div class="slide-right" id="slide-right"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191"
                                width="24" height="24" viewBox="0 0 24 24">
                                <path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z" />
                            </svg></div>
                    </div>
                </div>
                <!--/APP-SIDEBAR-->
            </div>

   